Project:
  type: object
  properties:
    id:
      $ref: '#/components/schemas/ID'
    name:
      type: string
      x-mock: '@ctitle'
    repository:
      type: string
      x-mock: 'https://github.com/@word(6)/@word(6).git'

    creator:
      x-$ref: '#/components/schemas/Admin'
      $ref: '#/components/schemas/ID'
    createAt:
      type: string
      format: date-time
      description: 创建时间
      x-mock: '@datetime'
    updateAt:
      type: string
      format: date-time
      description: 更新时间
      x-mock: '@datetime'

