Site:
  type: object
  description: 站点
  required:
    - name
  properties:
    id:
      type: integer
      format: int32
      description: 站点id
      x-mock: '@integer'
    name:
      type: string
      description: 站点名称
      x-mock: '@ctitle'
    description:
      type: string
      description: 站点描述
      x-mock: '@cparagraph'
    maxConcurrency:
      type: integer
      format: int32
      description: 最大并发数
      x-mock: '@integer(1,10000)'
    admins:
      type: array
      description: 管理员列表
      items:
        type: integer
        x-mock: '@integer'
        x-$ref: '#/components/schemas/Admin'
    #deviceGroups:
      #type: array
      #description: 同步组列表
      #items:
        #$ref: '#/components/schemas/DeviceGroup'
    #admins:
      #type: array
      #description: 管理员列表
      #items:
        #$ref: '#/components/schemas/Admin'
    #policies:
      #type: array
      #description: 策略列表
      #items:
        #$ref: '#/components/schemas/Policy'
    #tasks:
      #type: array
      #description: 任务列表
      #items:
        #$ref: '#/components/schemas/Task'

    creator:
      type: integer
      description: 创建人
      x-$ref: '#/components/schemas/Admin'
      x-mock: '@integer'
    createAt:
      type: string
      format: date-time
      description: 创建时间
      x-mock: '@datetime'
    updateAt:
      type: string
      format: date-time
      description: 更新时间
      x-mock: '@datetime'

